name: Build on Windows

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        branch: ['14.0']
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Install dependencies
      shell: cmd
      run: |
        C:\msys64\usr\bin\bash -lc "pacman -S mingw-w64-x86_64-nasm mingw-w64-x86_64-yasm mingw-w64-x86_64-meson mingw-w64-x86_64-ninja --noconfirm"
    - name: build
      shell: cmd
      run: |
        set MSYSTEM=MINGW64
        set HOME=${{ github.workspace }}
        set CFLAGS=-flto -v
        set CXXFLAGS=%CFLAGS%
        set LDFLAGS=-static -static-libgcc -flto -s
        git clone --depth 1 -b VTM-${{ matrix.branch }} https://vcgit.hhi.fraunhofer.de/jvet/VVCSoftware_VTM
        C:\msys64\usr\bin\bash -lc "cd VVCSoftware_VTM && mkdir gcc_cmake && cd gcc_cmake && cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Release"
        C:\msys64\usr\bin\bash -lc "cd VVCSoftware_VTM/gcc_cmake && ninja"
        for /r ".\VVCSoftware_VTM\bin\ninja" %%i in (*.exe) do copy "%%i" .\
        copy /y VVCSoftware_VTM\COPYING COPYING
        xcopy /e /i VVCSoftware_VTM\cfg cfg
    - name: Upload result
      uses: actions/upload-artifact@v2
      with:
        name: VVCSoftware_VTM_v${{ matrix.branch }}
        path: |
          *.exe
          COPYING
          cfg
